####By Amit Kumar

swagger: '2.0'
info:
  version: "0.0.1"
  title: XSS Vulnerable
  description: <img src=x onerror="confirm('1')">,<img src=y onerror="prompt('1')">
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
