####By Amit Kumar

swagger: '2.0'
info:
  version: "0.0.1"
  title: <SVG/Onload=prompt(2)>
  description: <img src=y onerror="prompt('1')">
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
